import { execFile } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const SECRET_NAMES = [
  "ANTHROPIC_API_KEY",
  "OPENAI_API_KEY",
  "GOOGLE_GENERATIVE_AI_API_KEY",
  "PERPLEXITY_API_KEY",
  "WEBHOOK_HMAC_SECRET",
  "ADMIN_API_KEY",
  "DATABASE_URL",
] as const;

async function readSecret(name: string): Promise<string> {
  const { stdout } = await execFileAsync("gcloud", [
    "secrets",
    "versions",
    "access",
    "latest",
    "--secret",
    name,
  ]);
  return stdout.trim();
}

const lines: string[] = [
  "# Generated by npm run secrets:pull",
  "# Do not commit this file.",
];

for (const name of SECRET_NAMES) {
  const value = await readSecret(name);
  lines.push(`${name}=${JSON.stringify(value)}`);
}

await writeFile(".env.local", `${lines.join("\n")}\n`, { mode: 0o600 });
console.log("Wrote .env.local with values from GCP Secret Manager.");
